import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { toPng } from 'html-to-image';
import { OffTargetHit, GuideRNA } from '../types';

export const generatePDFReport = async (
    guide: GuideRNA | { targetGene?: string, sequence?: string }, 
    hits: OffTargetHit[], 
    chartId: string,
    fileName: string
) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();
    
    // Colors
    const primaryColor = [14, 165, 233]; // science-500

    // Header
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text('CRISPR Off-Target Analysis', 14, 20);

    // Metadata Box
    doc.setDrawColor(200, 200, 200);
    doc.setFillColor(245, 247, 250);
    doc.rect(14, 28, 182, 35, 'FD');

    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    doc.text(`Date: ${date}`, 20, 36);
    doc.text(`Target Gene: ${guide.targetGene || 'Unknown'}`, 20, 42);
    doc.text(`Guide Sequence: ${guide.sequence || 'N/A'}`, 20, 48);
    
    // Stats
    const highRisk = hits.filter(h => h.cfdScore > 0.8).length;
    doc.text(`Total Off-Targets: ${hits.length}`, 110, 36);
    doc.text(`High Risk (>0.8): ${highRisk}`, 110, 42);
    doc.text(`Chromosomes Affected: ${new Set(hits.map(h => h.chromosome)).size}`, 110, 48);

    let yPos = 75;

    // Visualization Snapshot
    try {
        const chartNode = document.getElementById(chartId);
        if (chartNode) {
            // Need light background for PDF
            const imgData = await toPng(chartNode, { 
                backgroundColor: '#ffffff',
                quality: 0.9,
                filter: (n: any) => !n.classList?.contains('no-export')
            });
            doc.addImage(imgData, 'PNG', 14, yPos, 182, 100);
            yPos += 110;
        }
    } catch (e) {
        console.warn("Could not add chart to PDF", e);
        doc.text("Visualization could not be captured.", 14, yPos);
        yPos += 20;
    }

    // Top Risks Table
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Top 10 High-Risk Off-Targets', 14, yPos);
    yPos += 5;

    const topHits = [...hits]
        .sort((a, b) => b.cfdScore - a.cfdScore)
        .slice(0, 10)
        .map(h => [
            h.chromosome,
            h.position.toLocaleString(),
            h.geneName || '-',
            h.mismatches,
            h.cfdScore.toFixed(3),
            h.regionType
        ]);

    autoTable(doc, {
        startY: yPos,
        head: [['Chr', 'Pos', 'Gene', 'MM', 'Score', 'Region']],
        body: topHits,
        theme: 'striped',
        headStyles: { fillColor: [14, 165, 233] },
        styles: { fontSize: 9 }
    });

    // Disclaimer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by CRISPR Off-Target Visualizer. For research use only.", 14, pageHeight - 10);

    doc.save(`${fileName}.pdf`);
};
